import de.undercouch.gradle.tasks.download.Download
import de.undercouch.gradle.tasks.download.DownloadExtension
import org.gradle.kotlin.dsl.download
import org.gradle.kotlin.dsl.support.listFilesOrdered

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    kotlin("multiplatform") apply false
    kotlin("plugin.serialization") apply false
    id("com.gradleup.shadow") apply false
    id("de.undercouch.download")
}

allprojects {
    group = "moe.nikky"
    version = "1.0-SNAPSHOT"

    repositories {
        mavenCentral()
    }
}

val localKonanDir = project.provider {
    File(System.getenv("KONAN_DATA_DIR") ?: (System.getProperty("user.home") + File.separator + ".konan"))
}

val dependencyDllFiles = project.provider {
    localKonanDir.get()
        .also {
            logger.lifecycle("listing $it")
            logger.lifecycle(it.listFilesOrdered { true }.joinToString("\n"))
        }
        .resolve("dependencies")
//            .also { print(it.listFiles().joinToString("\n")) }
        .listFilesOrdered { it.isDirectory && it.name.startsWith("msys2-mingw") }
        .firstOrNull()// ?: error("cannot find msys2-mingw in konan dir ${localKonanDir.get()}")
        ?.let { msys2Mingw ->
            msys2Mingw.resolve("bin").listFilesOrdered { f ->
                f.extension == "dll" &&
                        f.nameWithoutExtension.startsWith("libstdc++") ||
                        f.nameWithoutExtension.startsWith("libgcc_s_seh") ||
                        f.nameWithoutExtension.startsWith("libwinpthread")
            }
        }.orEmpty()
}

val mingwDownloadDest = project.provider {
    layout.buildDirectory.file("download/msys2-mingw-w64-x86_64-2.zip").get().asFile
}

tasks {
    val downloadMsys2Mingw by registering(Download::class) {
        group = "package"
        src("https://download.jetbrains.com/kotlin/native/msys2-mingw-w64-x86_64-2.zip")
        dest(mingwDownloadDest)
        overwrite(false)
    }
    val unzipDependencyDlls by registering(Copy::class) {
        group = "package"

        dependsOn(downloadMsys2Mingw)
        from(
            zipTree(downloadMsys2Mingw.get().dest)
                .filter { f ->
                    f.parentFile.name == "bin" &&
                            f.extension == "dll" &&
                            listOf(
                                "libstdc++",
                                "libgcc_s_seh",
                                "libwinpthread",
                            ).any {
                                f.nameWithoutExtension.startsWith(it)
                            }
                }
        )
        into(layout.buildDirectory.file("unzip"))
    }
    val packageDependencies by registering(Zip::class) {
        group = "package"
        dependsOn(":dj-session-export:downloadKotlinNativeDistribution")

        from(unzipDependencyDlls)

        archiveBaseName = "dependencies"
        destinationDirectory = project.layout.buildDirectory
    }
    val packageZip by registering(Zip::class) {
        group = "package"
        dependsOn(":dj-session-export:downloadKotlinNativeDistribution")
        subprojects
            .forEach { subproject ->
                subproject.tasks.firstOrNull {
                    it.name == "linkReleaseExecutableMingwX64"
                }?.let {
                    from(it)
                }
            }
        subprojects
            .forEach { subproject ->
                subproject.tasks.firstOrNull {
                    it.name == "shadowJar"
                }?.let {
                    from(it)
                }
            }

        from(unzipDependencyDlls)
        archiveBaseName = "dist"
        destinationDirectory = project.layout.buildDirectory
    }
    val copyExecutables by registering(Copy::class) {
        group = "package"
        dependsOn(":dj-session-export:downloadKotlinNativeDistribution")
        dependsOn(packageDependencies)

        subprojects
            .forEach { subproject ->
                subproject.tasks.firstOrNull {
                    it.name == "linkReleaseExecutableMingwX64"
                }?.let {
                    from(it)
                }
            }
        subprojects
            .forEach { subproject ->
                subproject.tasks.firstOrNull {
                    it.name == "shadowJar"
                }?.let {
                    from(it)
                }
            }

        from(unzipDependencyDlls)

        destinationDir = file(project.layout.buildDirectory)
    }
}

