import org.gradle.kotlin.dsl.support.listFilesOrdered

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    kotlin("multiplatform") apply false
    kotlin("plugin.serialization") apply false
    id("com.gradleup.shadow") apply false
}

allprojects {
    group = "moe.nikky"
    version = "1.0-SNAPSHOT"

    repositories {
        mavenCentral()
    }
}

val localKonanDir = project.provider {
    File(System.getenv("KONAN_DATA_DIR") ?: (System.getProperty("user.home") + File.separator + ".konan"))
}

tasks {
    val packageDependencies by registering(Zip::class) {
        group = "package"

        val msys2Mingw = localKonanDir.get()
            .resolve("dependencies")
//            .also { print(it.listFiles().joinToString("\n")) }
            .listFilesOrdered { it.isDirectory && it.name.startsWith("msys2-mingw") }
            .firstOrNull() ?: error("cannot find msys2-mingw in konan dir ${localKonanDir.get()}")
        msys2Mingw.resolve("bin").listFilesOrdered { f ->
            f.extension == "dll" &&
                    f.nameWithoutExtension.startsWith("libstdc++") ||
                    f.nameWithoutExtension.startsWith("libgcc_s_seh") ||
                    f.nameWithoutExtension.startsWith("libwinpthread")
        }.forEach {
            from(it)
        }

        archiveBaseName = "dependencies"
        destinationDirectory = project.layout.buildDirectory
    }
    val packageZip by registering(Zip::class) {
        group = "package"
        subprojects
            .forEach { subproject ->
                subproject.tasks.firstOrNull {
                    it.name == "linkReleaseExecutableMingwX64"
                }?.let {
                    from(it)
                }
            }
        subprojects
            .forEach { subproject ->
                subproject.tasks.firstOrNull {
                    it.name == "shadowJar"
                }?.let {
                    from(it)
                }
            }
        val msys2Mingw = localKonanDir.get()
            .resolve("dependencies")
//            .also { print(it.listFiles().joinToString("\n")) }
            .listFilesOrdered { it.isDirectory && it.name.startsWith("msys2-mingw") }
            .firstOrNull() ?: error("cannot find msys2-mingw in konan dir ${localKonanDir.get()}")
        msys2Mingw.resolve("bin").listFilesOrdered { f ->
            f.extension == "dll" &&
                    f.nameWithoutExtension.startsWith("libstdc++") ||
                    f.nameWithoutExtension.startsWith("libgcc_s_seh") ||
                    f.nameWithoutExtension.startsWith("libwinpthread")
        }.forEach {
            from(it)
        }
        archiveBaseName = "dist"
        destinationDirectory = project.layout.buildDirectory
    }
    val copyExecutables by registering(Copy::class) {
        group = "package"
        dependsOn(packageDependencies)

        subprojects
            .forEach { subproject ->
                subproject.tasks.firstOrNull {
                    it.name == "linkReleaseExecutableMingwX64"
                }?.let {
                    from(it)
                }
            }
        subprojects
            .forEach { subproject ->
                subproject.tasks.firstOrNull {
                    it.name == "shadowJar"
                }?.let {
                    from(it)
                }
            }
        val msys2Mingw = localKonanDir.get()
            .resolve("dependencies")
//            .also { print(it.listFiles().joinToString("\n")) }
            .listFilesOrdered { it.isDirectory && it.name.startsWith("msys2-mingw") }
            .firstOrNull() ?: error("cannot find msys2-mingw in konan dir ${localKonanDir.get()}")
        msys2Mingw.resolve("bin").listFilesOrdered { f ->
            f.extension == "dll" &&
                    f.nameWithoutExtension.startsWith("libstdc++") ||
                    f.nameWithoutExtension.startsWith("libgcc_s_seh") ||
                    f.nameWithoutExtension.startsWith("libwinpthread")
        }.forEach {
            from(it)
        }

        destinationDir = file(project.layout.buildDirectory)
    }
}

