/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    kotlin("multiplatform") apply false
    kotlin("plugin.serialization") apply false
}

allprojects {
    group = "moe.nikky"
    version = "1.0-SNAPSHOT"

    repositories {
        mavenCentral()
    }
}

tasks {
    val packageZip by registering(Zip::class) {
        group = "package"
        subprojects
            .forEach { subproject ->
                subproject.tasks.firstOrNull {
                    it.name == "linkReleaseExecutableMingwX64"
                }?.let {
                    from(it)
                }
            }
        archiveBaseName = "dist"
        destinationDirectory = project.layout.buildDirectory
    }
    val copyExecutables by registering(Copy::class) {
        group = "package"

        subprojects
            .forEach { subproject ->
                subproject.tasks.firstOrNull {
                    it.name == "linkReleaseExecutableMingwX64"
                }?.let {
                    from(it)
                }
            }
        destinationDir = file(project.layout.buildDirectory)
    }
}

