/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
pluginManagement {
    includeBuild("build-logic")
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
    // See https://jmfayard.github.io/refreshVersions
    id("de.fayard.refreshVersions") version "0.60.6"
}

rootProject.name = "dj-session-export-root"

include("shared")

include("traktor-convert")
include("serato-convert")

include("traktor-export")
include("serato-export")
include("rekordbox-export")
include("mixxx-export")
//include("djay-export")
include("virtualdj-export")
include("dj-session-export")
